### ISSUE TITLE
Is incremental coverage supported?

### ISSUE THREAD

**Issue by xhd2015** [kilianc/go-beautiful-html-coverage#35]
Xgo is working on a similar tool, the UI is still under refactoring. And I see this repository is doing this.

Are you going to support incremental coverage and CLI tool to display locally?

https://github.com/xhd2015/xgo/pull/106

**Comment by xhd2015** [comment]
Chances are, maybe xgo can opt in into this tool?

**Comment by kilianc** [comment]
sure, what are the requirements?

**Comment by xhd2015** [comment]
> sure, what are the requirements?

When working a large code base, reviewing coverage of each file sucks as there were too many files.

Incremental coverage is a way to improve this experience. It filters out files not changed compared with master or main, which can be achieved by doing a git diff. And more, it should also filter out lines not changed within updated file.

This way, only changed code need a care on coverage.

How do you think?

**Comment by kilianc** [comment]
Understood, let me think about how to do it. see https://github.com/gha-common/go-beautiful-html-coverage/issues/15

**Comment by kilianc** [comment]
@xhd2015 can you open a pr here to create `cover.out` with your tool [here](https://github.com/gha-common/go-beautiful-html-coverage/blob/main/go-test-app-01/Makefile#L3)? I want to see what it looks like.

edit --

doesn't look like your tool does the incremental part, is the .out file generated by go tool?

**Comment by xhd2015** [comment]
> @xhd2015 can you open a pr here to create `cover.out` with your tool [here](https://github.com/gha-common/go-beautiful-html-coverage/blob/main/go-test-app-01/Makefile#L3)? I want to see what it looks like.
> 
> edit --
> 
> doesn't look like your tool does the incremental part, is the .out file generated by go tool?

Sure, let me do this later.

Actually it does, but that part of code is still being open-sourcing. So now only binary is released.But soon the code will be opened.

**Comment by kilianc** [comment]
would simply diffing main.out and current.out work?

**Comment by xhd2015** [comment]
> would simply diffing main.out and current.out work?

Maybe. I can try that

**Comment by xhd2015** [comment]
> can you open a pr here to create cover.out with your tool [here](https://github.com/gha-common/go-beautiful-html-coverage/blob/main/go-test-app-01/Makefile#L3)? I want to see what it looks like.

@kilianc I think I misunderstood you. The xgo tool does not generate a cover profile. Actually it converts that profile into a web-based UI in combination  with git diff, hence the so called incremental.

**Comment by kilianc** [comment]
I think that diffing the `cover.out` and then creating the html will work. I am a bit sick but I will be able to write some tests in the next few days.

**Comment by kilianc** [comment]
it works: https://github.com/gha-common/go-beautiful-html-coverage/pull/39

**Comment by kilianc** [comment]
making some progress on having dark and light themes from github and refining the UI.

<img width="421" alt="image" src="https://github.com/gha-common/go-beautiful-html-coverage/assets/385716/812689da-d63d-4ef6-ac85-5649e391ef9f">

I don't think it will be as feature rich as the one you posted tho.

**Comment by xhd2015** [comment]
> making some progress on having dark and light themes from github and refining the UI.
> 
> <img alt="image" width="421" src="https://private-user-images.githubusercontent.com/385716/331320573-812689da-d63d-4ef6-ac85-5649e391ef9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTA5MDYsIm5iZiI6MTcxNTkxMDYwNiwicGF0aCI6Ii8zODU3MTYvMzMxMzIwNTczLTgxMjY4OWRhLWQ2M2QtNGVmNi1hYzg1LTU2NDllMzkxZWY5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwMTUwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmZlOGM2MDM3NDdiN2NhNTIyYzRkNjYyYTc0MjEzZGI2YWVmY2U0MDc3NWVhMTFlYjY2N2UyMzJmNDNiZGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8sc0Daj7TsKas0U0qRaM8d7iX4kO4E7Jm9WYMSkI-SA">
> I don't think it will be as feature rich as the one you posted tho.

Amazing! At least this is the first step to make it work!

**Comment by kilianc** [comment]
UI progress https://kilianc.github.io/pretender/test/#file0

<img width="1264" alt="image" src="https://github.com/gha-common/go-beautiful-html-coverage/assets/385716/dab27c1b-9571-42c6-b5ec-9073bb955627">

<img width="1264" alt="image" src="https://github.com/gha-common/go-beautiful-html-coverage/assets/385716/dfd2ce5d-0ffc-493b-9d78-4be316a418e8">

<img width="1005" alt="image" src="https://github.com/gha-common/go-beautiful-html-coverage/assets/385716/7a7a82a1-a2d2-4e0f-8905-5853510b2690">

<img width="1005" alt="image" src="https://github.com/gha-common/go-beautiful-html-coverage/assets/385716/ae66299a-dae5-4c3d-9c1a-c27c8c4df9c7">

**Comment by kilianc** [comment]
Just merged into [main](https://github.com/gha-common/go-beautiful-html-coverage), I need to add a "incremental button" to the UI and then I'll focus on the CLI.

@xhd2015 how do you get information about your base branch in your tooling? For example in `feature-a` branch, how do you compare it `main`? do you checkout `main` and run the tests? Is the coverage saved somewhere?

If this was a cli, like `go run go-beautiful-html-coverage` what would be the arguments?

**Comment by xhd2015** [comment]
> Just merged into [main](https://github.com/gha-common/go-beautiful-html-coverage), I need to add a "incremental button" to the UI and then I'll focus on the CLI.
> 
> @xhd2015 how do you get information about your base branch in your tooling? For example in `feature-a` branch, how do you compare it `main`? do you checkout `main` and run the tests? Is the coverage saved somewhere?
> 
> If this was a cli, like `go run go-beautiful-html-coverage` what would be the arguments?

This part of diffing is not open sourced yet, I'll work on this later.

Basically it just uses the `exec.Command` to spawn some `git diff` process and capture the output.

**Comment by kilianc** [comment]
but that's not enough to diff the coverage, a change on `foo.go#13` might affect coverage of `func Bar` in `bar.go#56`. The diff won't help you understand the impact of your code changes on coverage.

You need a full coverage diff against the base branch of your PR. When running locally, where do you get the coverage from? run the tests on `main` and cache them?

**Comment by xhd2015** [comment]
Oh so you are right, I missed the affect-chain problems... Currently only static diff is considered

**Comment by kilianc** [comment]
closing this for now
